export enum ErrorCategoryEnum {
  CALLER_WRONG_USAGE_ERROR = 'caller_wrong_usage_error',
  CALLER_WRONG_DOMAIN_ERROR = 'caller_wrong_domain_error',
  SUPPLIER_SYSTEM_ERROR = 'supplier_system_error',
  INTERNAL_DOMAIN_ERROR = 'internal_domain_error',
}

export enum ErrorSubCategoryEnum {
  INVALID_INPUT = 'invalid_input',
  UNEXPECTED_STATUS = 'unexpected_status',
  NO_DATA = 'no_data',
  INTERNAL_ERROR = 'internal_error',
}

export enum ErrorCodeEnum {
  // Caller wrong usage error (1000-1999)
  INVALID_INPUT = 'ERR1001',
  MISSING_REQUIRED_FIELD = 'ERR1002',
  INVALID_FORMAT = 'ERR1003',
  INVALID_NICKNAME = 'ERR1004',
  INVALID_NICKNAME_FORMAT = 'ERR1005',
  DUPLICATE_NIKCNAME = 'ERR1006',
  DUPLICATE_RESTAURANT_NAME = 'ERR1007',
  NO_REVIEW_DATA = 'ERR1008',
  INVALID_RESTAURANT = 'ERR1009',
  MISSING_USER_AREA = 'ERR1010',
  MISSING_EXTERNAL_RESTAURANT = 'ERR1011',
  INVALID_CREDENTIALS = 'ERR1012',
  INVALID_AUTH_CODE = 'ERR1014',
  ACCOUNT_NOT_FOUND = 'ERR1015',
  AUTH_CODE_EXPRIED = 'ERR1016',
  INVALID_AUTH_STATE = 'ERR1017',
  DUPLICATE_AUTH_REQUEST = 'ERR1018',
  DUPLICATE_IDENTIFICATION = 'ERR1019',
  INVALID_AUTH_TYPE = 'ERR1020',
  INVALID_SOCIAL_AUTH_TYPE = 'ERR1021',

  // Caller Wrong Domain Error (2000-2999)
  RESOURCE_NOT_FOUND = 'ERR2001',

  // Supplier System Error (3000-3999)
  EXTERNAL_SERVICE_ERROR = 'ERR3001',
  TIMEOUT_ERROR = 'ERR3002',

  // Internal Domain Error (5000-5999)
  INTERNAL_SERVER_ERROR = 'ERR5001',
}
