version: '3.8'

services:
  postgis-db:
    image: postgis/postgis
    restart: always
    container_name: 'taste-dict-rds'
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taste
    networks:
      - taste_dict_network
  cache:
    image: redis:7.0-alpine
    container_name: 'tast-dict-cache'
    restart: always
    ports:
      - 6399:6379
    command: redis-server
    volumes: 
      - ./cache:/data
    networks:
      - taste_dict_network
volumes:
  taste-dict-rds:
    driver: local
  taste-dict-cache:
    driver: local
networks:
  taste_dict_network: