version: '3.8'

services:
  db:
    image: postgres:9.6
    restart: always
    container_name: 'db'
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taste
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - dev_network
  cache:
    image: redis:7.0-alpine
    container_name: 'cache'
    restart: always
    ports:
      - 6399:6379
    command: redis-server
    volumes: 
      - ./cache:/data
    networks:
      - dev_network
volumes:
  db:
    driver: local
  cache:
    driver: local
networks:
  dev_network: