
### create progress
POST {{base_url}}/v1/authentication/account
Content-Type: {{content_type_json}}

{
  "identification": "wkdgndldi@naver.com",
  "category":"account",
  "type":"email"
}

### create progress
POST {{base_url}}/v1/authentication/password
Content-Type: {{content_type_json}}

{
  "identification": "wkdgndldi@naver.com",
  "category":"password",
  "type":"email"
}


### donw progress
POST {{base_url}}/v1/authentication/status/done
Content-Type: {{content_type_json}}

{
  "historyId": 48,
  "code":"612068"
}