### get token(use after register user)
# @name token
post {{base_url}}/v1/account/tokens
content-type: {{content_type_json}}

{
  "identification": "matthew-1023",
  "password": "pwd",
  "category": "email"
}

###
@access_token = {{token.response.body.data.accessToken}}

### Register review
POST {{base_url}}/v1/restaurant/review
Authorization: Bearer {{access_token}}
Content-Type: {{content_type_json}}

{
    "review":{
        "category":"분식",
        "keywords":["test2"],
        "price":10000,
        "summary":"one-line summary",
        "opinion":"Y"
    },
    "external":{
        "externalUUID":8323721,
        "name":"버드나무집 서초본점",
        "latitude":37.48913764364786,
        "longitude":127.0311629855974,
        "referenceLink":"http://place.map.kakao.com/8323721"
    }
}

### get recommenda tion
POST {{base_url}}/v1/restaurant/recommendation
Authorization: Bearer {{access_token}}
Content-Type: {{content_type_json}}

{
    "excludeIds": [],
    "category": "분식",
    "keywords": ["test2"],
    "price": 10000
}