
### Register User 
POST {{base_url}}/v1/user
Content-Type: {{content_type_json}}

{
  "userProperty": {
    "companyName": "test"
  },
  "areas": [
    {
      "latitude": 37.48913764364786,
      "longitude": 127.0311629855974,
      "category": "activity_area",
      "address":"activity"
    },
    {
      "latitude": 37.48913764364786,
      "longitude": 127.0311629855974,
      "category": "dining_area",
      "address":"dining"
    }
  ],
  "account": {
    "identification": "matthew-0917",
    "password": "pwd",
    "category": "email"
    
  },
  "agreements": [
    {
      "category": "personal_information",
      "is_agree": true
    }
  ]
}


### get token(use after register user)
# @name token
post {{base_url}}/v1/account/tokens
content-type: {{content_type_json}}

{
  "identification": "matthew-0917",
  "password": "pwd",
  "category": "email"
}

###
@access_token = {{token.response.body.data.accessToken}}


### get profile 
GET {{base_url}}/v1/user/profile
Authorization: Bearer {{access_token}}
Content-Type: {{content_type_json}}

### modify user area
PUT {{base_url}}/v1/user
Authorization: Bearer {{access_token}}
Content-Type: {{content_type_json}}

{
      "latitude": 100,
      "longitude": 100,
      "category": "activity_area",
      "address":"activity-update"
}

### delete user
DELETE  {{base_url}}/v1/user
Authorization: Bearer {{access_token}}
Content-Type: {{content_type_json}}

{
  "type":"inconvenient_usage"
}
