FROM node:18.10.0-alpine

WORKDIR /usr/src/app

COPY package*.json .
COPY prisma ./prisma/

ENV NODE_ENV=prod

RUN npm ci
RUN npx prisma generate

COPY . .

RUN npm run build

EXPOSE 8080

CMD [ "node", "dist/src/main.js" ]