"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.nestia = exports.error = void 0;
/**
 * @packageDocumentation
 * @module api.functional.v1.playground
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
exports.error = require("./error");
exports.nestia = require("./nestia");
