"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.v1 = void 0;
/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
exports.v1 = require("./v1");
