"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.postSample = void 0;
/**
 * @packageDocumentation
 * @module api.functional.v1.playground.nestia
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
const fetcher_1 = require("@nestia/fetcher");
/**
 * @controller PlaygroundController.postSample()
 * @path POST /v1/playground/nestia
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
function postSample(connection, dto) {
    var _a;
    return __awaiter(this, void 0, void 0, function* () {
        return fetcher_1.Fetcher.fetch(Object.assign(Object.assign({}, connection), { headers: Object.assign(Object.assign({}, ((_a = connection.headers) !== null && _a !== void 0 ? _a : {})), { "Content-Type": "application/json" }) }), postSample.ENCRYPTED, postSample.METHOD, postSample.path(), dto);
    });
}
exports.postSample = postSample;
(function (postSample) {
    postSample.METHOD = "POST";
    postSample.PATH = "/v1/playground/nestia";
    postSample.ENCRYPTED = {
        request: false,
        response: false,
    };
    postSample.path = () => {
        return `/v1/playground/nestia`;
    };
})(postSample || (exports.postSample = postSample = {}));
