/**
 * @packageDocumentation
 * @module api.functional.v1.playground.nestia
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import { Fetcher } from "@nestia/fetcher";
import type { IConnection, Primitive } from "@nestia/fetcher";
import type { PlaygroundSampleDto } from "./../../../../../domain/playground/dto/playground.dto";
/**
 * @controller PlaygroundController.postSample()
 * @path POST /v1/playground/nestia
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function postSample(connection: IConnection, dto: postSample.Input): Promise<postSample.Output>;
export declare namespace postSample {
    type Input = Primitive<PlaygroundSampleDto>;
    type Output = Primitive<PlaygroundSampleDto>;
    const METHOD: "POST";
    const PATH: string;
    const ENCRYPTED: Fetcher.IEncrypted;
    const path: () => string;
}
