"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.createError = void 0;
/**
 * @packageDocumentation
 * @module api.functional.v1.playground.error
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
const fetcher_1 = require("@nestia/fetcher");
/**
 * @controller PlaygroundController.createError()
 * @path GET /v1/playground/error
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
function createError(connection) {
    return __awaiter(this, void 0, void 0, function* () {
        return fetcher_1.Fetcher.fetch(connection, createError.ENCRYPTED, createError.METHOD, createError.path());
    });
}
exports.createError = createError;
(function (createError) {
    createError.METHOD = "GET";
    createError.PATH = "/v1/playground/error";
    createError.ENCRYPTED = {
        request: false,
        response: false,
    };
    createError.path = () => {
        return `/v1/playground/error`;
    };
})(createError || (exports.createError = createError = {}));
