/**
 * @packageDocumentation
 * @module api.functional.v1.playground.error
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import { Fetcher } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";
/**
 * @controller PlaygroundController.createError()
 * @path GET /v1/playground/error
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function createError(connection: IConnection): Promise<void>;
export declare namespace createError {
    const METHOD: "GET";
    const PATH: string;
    const ENCRYPTED: Fetcher.IEncrypted;
    const path: () => string;
}
