/**
 * @packageDocumentation
 * @module api.functional.v1.configuration
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import { Fetcher } from "@nestia/fetcher";
import type { IConnection, Primitive } from "@nestia/fetcher";
import type { ServerConfig } from "./../../../../domain/configuration/dto/configuration.dto";
export * as server_status from "./server_status";
/**
 * @controller V1ConfigurationController.getServerConfig()
 * @path GET /v1/configuration
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getServerConfig(connection: IConnection): Promise<getServerConfig.Output>;
export declare namespace getServerConfig {
    type Output = Primitive<ServerConfig>;
    const METHOD: "GET";
    const PATH: string;
    const ENCRYPTED: Fetcher.IEncrypted;
    const path: () => string;
}
