name: build_and_push

on:
  release:
    types: [published]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set .npmrc
        run: |
          echo "//npm.pkg.github.com//:_authToken=${{ secrets.NPM_AUTH_TOKEN }}\n@homekeeper89:registry=https://npm.pkg.github.com" > ~/.npmrc
          
      - name: Bump to new version
        run: |
          git config user.name "taste-bot"
          git config user.email "noreply@github.com"
          git switch -c bump-${{ github.REF_NAME }}
          npm version ${{ github.REF_NAME }} -m "bump to ${{ github.REF_NAME }}"
          npm run package:publish
          git push --set-upstream origin bump-${{ github.REF_NAME }}
          gh pr create --title "bump to ${{ github.REF_NAME }}" --body "bump to ${{ github.REF_NAME }}" --base main --head bump-${{ github.REF_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCP registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/taste-server:latest
            ${{ secrets.DOCKER_REGISTRY }}/taste-server:${{ github.REF_NAME }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/taste-server:latest
          cache-to: type=inline