"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.getServerStatus = void 0;
/**
 * @packageDocumentation
 * @module api.functional.v1.configuration.server_status
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
const fetcher_1 = require("@nestia/fetcher");
/**
 * @controller V1ConfigurationController.getServerStatus()
 * @path GET /v1/configuration/server-status
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
function getServerStatus(connection) {
    return __awaiter(this, void 0, void 0, function* () {
        return fetcher_1.Fetcher.fetch(connection, getServerStatus.ENCRYPTED, getServerStatus.METHOD, getServerStatus.path());
    });
}
exports.getServerStatus = getServerStatus;
(function (getServerStatus) {
    getServerStatus.METHOD = "GET";
    getServerStatus.PATH = "/v1/configuration/server-status";
    getServerStatus.ENCRYPTED = {
        request: false,
        response: false,
    };
    getServerStatus.path = () => {
        return `/v1/configuration/server-status`;
    };
})(getServerStatus || (exports.getServerStatus = getServerStatus = {}));
