/**
 * @packageDocumentation
 * @module api.functional.v1.configuration.server_status
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
import { Fetcher } from "@nestia/fetcher";
import type { IConnection, Primitive } from "@nestia/fetcher";
import type { ServerMetaData } from "./../../../../../domain/configuration/dto/configuration.dto";
/**
 * @controller V1ConfigurationController.getServerStatus()
 * @path GET /v1/configuration/server-status
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export declare function getServerStatus(connection: IConnection): Promise<getServerStatus.Output>;
export declare namespace getServerStatus {
    type Output = Primitive<ServerMetaData>;
    const METHOD: "GET";
    const PATH: string;
    const ENCRYPTED: Fetcher.IEncrypted;
    const path: () => string;
}
